spring:
  datasource:
    url: jdbc:oracle:thin:@${ORACLE_HOST:localhost}:${ORACLE_PORT:1521}/${ORACLE_DATABASE:template_app}
    username: ${ORACLE_USER:template}
    password: ${ORACLE_PASSWORD:1q2w3e4r5t6y}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        default_schema: ${HIBERNATE_DEFAULT_SCHEMA:template}
  jackson:
    time-zone: UTC

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
