spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  hibernate:
    ddl-auto: update
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
