spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@//template-oracle-db-build:1521/XE}
    username: ${SPRING_DATASOURCE_USERNAME:TEMPLATE_APP}
    password: ${SPRING_DATASOURCE_PASSWORD:darkSide123}
    driverClassName: oracle.jdbc.OracleDriver
    hikari:
      data-source-properties:
        oracle:
          jdbc:
            timezoneAsRegion: false
  jpa:
    databasePlatform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          timeZone: UTC
        defaultSchema: ${HIBERNATE_DEFAULT_SCHEMA:TEMPLATE_APP}
  jackson:
    time-zone: UTC

server:
  port: ${SERVER_PORT:8080}
  servlet:
    contextPath: /api

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
