version: "3.9"

services:
  # Java 17 Spring Boot Development Container
  template-java-17-spring-devcontainer:
    build:
      context: .. # Yep, we're going up one directory; it's not a bug, it's a feature!
      dockerfile: .devcontainer/Dockerfile.backend
    container_name: template-java-17-spring-devcontainer # A name as long as the build time on a slow day.
    image: napalm23zero/template-java-17-spring-devcontainer # Custom image, because default is too mainstream.
    ports:
      - "6080:8080" # Remapped to 6080 because 8080 is just too obvious.
    volumes:
      - ../:/workspace # Your entire project, containerized!
      - shared-maven-cache:/root/.m2 # Shared Maven cache because time is money and you know it.
    env_file:
      - .env # Shh, secrets!
    depends_on:
      template-oracle-db-devcontainer: 
        condition: service_healthy  # Depends on Oracle, because all great things have dependencies.
    networks:
      - templates
    logging:
      driver: "json-file" # Because we need logs, and JSON is the chosen one.
      options:
        max-size: "10m" # Cap log size at 10 MB, because who reads beyond that?
        max-file: "3" # Rotate after 3 logs, because history is overrated.
    command: ["sh", "-c", "trap 'docker-compose stop' EXIT; while :; do sleep 1; done"] # Ensures all services stop when this container stops

  # Oracle Database Development Container
  template-oracle-db-devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.database
    container_name: template-oracle-db-devcontainer # The bedrock of your data kingdom.
    ports:
      - "6521:1521" # Because sometimes, changing one digit is all the creativity you need.
    volumes:
      - template-oracle-db-data:/opt/oracle/oradata # Where your data sleeps at night.
    env_file:
      - .env # More secrets, shh!
    restart: always # Keeps coming back like a bad habit.
    environment: # Use environment variables, because hardcoding is for maniacs!
      ORACLE_PASSWORD: ${ORACLE_PASSWORD} # Oracle password, not to be confused with your Netflix password.
      ORACLE_DATABASE: ${ORACLE_DATABASE} # Your glorious database name.
      APP_USER: ${ORACLE_USER} # App user because 'admin' is too mainstream.
      APP_USER_PASSWORD: ${ORACLE_PASSWORD} # App user password, equally secret.
    networks:
      - templates
    healthcheck:
      test: [
          "CMD-SHELL",
          "echo 'SELECT 1 FROM DUAL;' | sqlplus -s SYSTEM/${ORACLE_PASSWORD}@localhost:1521/${ORACLE_DATABASE}",
        ] # Checking the database health because zombies aren't allowed.
      interval: 30s # Every 30 seconds, because patience is for the weak.
      timeout: 10s # If it takes longer than 10 seconds, something's definitely wrong.
      retries: 5 # Try 5 times before giving up, like most developers.
    logging:
      driver: "json-file" # Again, JSON logs because we need consistency in our lives.
      options:
        max-size: "10m" # 10 MB log cap, because less is more.
        max-file: "3" # Rotate after 3 logs, to keep things fresh.

volumes:
  template-oracle-db-data:
    driver: local # Locally stored, because we like to keep our toys close.
  shared-maven-cache:
    driver: local # Shared Maven cache for all your dependency caching needs.

networks:
  templates:
    driver: bridge # Bridging connections like social networks.
