spring:
  datasource:
    url: jdbc:oracle:thin:@//template-oracle-db:1521/XE
    username: TEMPLATE_APP
    password: darkSide123
    driverClassName: oracle.jdbc.OracleDriver
    hikari:
      data-source-properties:
        oracle.jdbc.timezoneAsRegion: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        jdbc:
          timeZone: UTC
        defaultSchema: TEMPLATE_APP
  jackson:
    time-zone: UTC

server:
  port: 8080
  servlet:
    contextPath: /api

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
