version: "3.8"
services:
  template-java-17-spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: template-java-17-spring
    image: napalm23zero/template-java-17-spring
    ports:
      - "6080:8080"
    volumes:
      - ../:/workspace
      - ${HOME}/.m2:/root/.m2
    depends_on:
      - template-oracle-db

  template-oracle-db:
    container_name: template-oracle-db
    image: oracleinanutshell/oracle-xe-11g
    ports:
      - "6521:1521"
    environment:
      ORACLE_ALLOW_REMOTE: "true"
      ORACLE_PASSWORD: darkSide123
      TZ: "Etc/UTC"
    volumes:
      - oracle-data:/u01/app/oracle
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  oracle-data:
    driver: local

networks:
  default:
    external:
      name: napalm23zero
