version: "3.8"
services:
  template-java-17-spring-devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.backend
    container_name: template-java-17-spring-devcontainer
    image: napalm23zero/template-java-17-spring-devcontainer
    ports:
      - "6080:8080"
    volumes:
      - ../:/workspace
      - ${HOME}/.m2:/root/.m2
    env_file:
      - ../.env
    depends_on:
      - template-oracle-db-devcontainer

  template-oracle-db-devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.database
    container_name: template-oracle-db-devcontainer
    restart: always
    ports:
      - "6521:1521"
    volumes:
      - template-oracle-db-data:/opt/oracle/oradata
    env_file:
      - ../.env
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      ORACLE_DATABASE: ${ORACLE_DATABASE}
      APP_USER: ${ORACLE_USER}
      APP_USER_PASSWORD: ${ORACLE_PASSWORD}

volumes:
  template-oracle-db-data:
    driver: local

networks:
  templates:
    driver: bridge