version: "3.8"

services:
  template-java-17-spring-build:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: template-java-17-spring-build
    image: napalm23zero/template-java-17-spring-build
    ports:
      - "8080:8080" # Expose the app on port 8080
    depends_on:
      - template-oracle-db-build # Ensure the DB starts before the app
    environment: # [this is just for fun, NO PRODUCTION!] [IF PRODUCTION CHANGE IT!!!!!]
      SPRING_DATASOURCE_URL: # JDBC connection string
      SPRING_DATASOURCE_USERNAME: # Database username
      SPRING_DATASOURCE_PASSWORD: # Database password
      HIBERNATE_DEFAULT_SCHEMA: # Default schema for Hibernate
      SERVER_PORT: # Server port

  template-oracle-db-build:
    container_name: template-oracle-db-build
    image: gvenzl/oracle-xe:21.3.0-slim # Use Oracle XE 21.3.0 because we like to live on the edge
    ports:
      - "1521:1521" # Expose Oracle DB on port 1521 (Default Oracle port)
    environment:
      ORACLE_PASSWORD: darkSide123 # Database password (Join the dark side, we have cookies)
      ORACLE_CHARACTERSET: AL32UTF8 # Set character set to UTF-8
      TZ: "UTC" # Set timezone to UTC
    volumes:
      - oracle-data:/opt/oracle/oradata # Persist database data
      - ./init.sql:/container-entrypoint-startdb.d/init.sql:ro # Initialize DB with this script (Make sure it's there, or suffer the consequences)

volumes:
  oracle-data:
    driver: local # Use local driver for volume (Keep your data close, and your volumes closer)
