version: "3.8"
services:

  template-java-17-spring-build:
    build:
      context: ..
      dockerfile: .docker/Dockerfile.backend
    container_name: template-java-17-spring-build
    image: napalm23zero/template-java-17-spring-build
    ports:
      - "6080:8080"
    volumes:
      - ../:/workspace
      - ${HOME}/.m2:/root/.m2
    env_file:
      - ../.env
    depends_on:
      template-oracle-db-build:
        condition: service_healthy

  template-oracle-db-build:
    build:
      context: ..
      dockerfile: .docker/Dockerfile.database
    container_name: template-oracle-db-build
    ports:
      - "1521:1521"
    restart: always
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      ORACLE_DATABASE: ${ORACLE_DATABASE}
      APP_USER: ${ORACLE_USER}
      APP_USER_PASSWORD: ${ORACLE_PASSWORD}
    volumes:
      - template-oracle-db-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -S ${ORACLE_USER}/${ORACLE_PASSWORD}@//localhost:1521/${ORACLE_DATABASE}"]
      interval: 30s
      timeout: 10s
      retries: 10

volumes:
  template-oracle-db-data:
    driver: local
