version: "3.8"

services:
  # The java application that will be built and run.
  template-java-17-spring-build:
    build:
      context: .. # Because the local directory is 2007
      dockerfile: .docker/Dockerfile.backend # Backend Dockerfile, because we're organized.
    container_name: template-java-17-spring-build # To avoid getting lost in the sea of containers.
    image: napalm23zero/template-java-17-spring-build # Custom image, we are custom baby!
    ports:
      - "8080:8080" # Because communication should be transparent.
    volumes:
      - ../:/workspace # Entire project, encapsulated!
      - shared-maven-cache:/root/.m2 # Maven cache, because waiting is for amateurs.
    env_file:
      - .env # shhh, secrets!
    depends_on:
      template-oracle-db-build:
        condition: service_healthy # No healthy DB, no startup. Simple as that.
    networks:
      - templates # Custom network, because we can.
    logging:
      driver: "json-file" # JSON logs, because we need to read them later.
      options:
        max-size: "10m" # Log size capped at 10MB, because less is more.
        max-file: "3" # Rotate after 3 logs, to keep things fresh.
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 30s # Check health every 30 seconds, because we're paranoid.
      timeout: 10s # Timeout after 10 seconds, because time is precious.
      retries: 3 # Retry 3 times, because who gives up after the first try?

  # The database, because Java alone is boring.
  template-oracle-db-build:
    build:
      context: .. # Reaching out of the directory, because boundaries are for the weak.
      dockerfile: .docker/Dockerfile.database # Different Dockerfile for our DB, because we are organized AF!!!
    container_name: template-oracle-db-build # This container is the cornerstone of our data empire.
    ports:
      - "1521:1521" # Data port, if you know what you're doing.
    restart: always # Like a phoenix, it rises from the ashes automatically.
    environment: # Environment variables, because we're not maniacs.
      ORACLE_PASSWORD: ${ORACLE_PASSWORD} 
      ORACLE_DATABASE: ${ORACLE_DATABASE}
      APP_USER: ${ORACLE_USER}
      APP_USER_PASSWORD: ${ORACLE_PASSWORD}
    volumes:
      - template-oracle-db-data:/opt/oracle/oradata # Persistent data, because amnesia is bad.
    env_file:
      - .env # More secrets, shhh!
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s SYSTEM/${ORACLE_PASSWORD}@localhost:1521/${ORACLE_DATABASE}"]
      interval: 30s # Health check every 30 seconds, because why not?
      timeout: 10s # Timeout after 10 seconds, time waits for no one.
      retries: 5 # Retry 5 times, because persistence pays off.
    networks:
      - templates # Custom network, because we're fancy.
    logging:
      driver: "json-file" # JSON logs, because consistency is key.
      options:
        max-size: "10m" # Log size capped at 10MB, because who reads more?
        max-file: "3" # Rotate after 3 logs, to keep things tidy.

volumes:
  template-oracle-db-data:
    driver: local # Local storage, keeping it close.
  shared-maven-cache:
    driver: local # Shared Maven cache, because dependencies are a pain.

networks:
  templates:
    driver: bridge # Bridging connections like social networks.
