apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: template-java-app
  template:
    metadata:
      labels:
        app: template-java-app
    spec:
      containers:
        - name: template-java-app
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/template-java-17-spring-oracle:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:oracle:thin:@//oracle-db-service:1521/XE"
            - name: SPRING_DATASOURCE_USERNAME
              value: "TEMPLATE_APP"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "darkSide123"
            - name: HIBERNATE_DEFAULT_SCHEMA
              value: "TEMPLATE_APP"
            - name: SERVER_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: template-java-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: template-java-app
